const { PermissionsBitField, EmbedBuilder, Colors } = require('discord.js');
const fs = require('fs');
const path = require('path');

const DATA_PATH = path.join(__dirname, '../data/channels.json');
const BACKUP_DIR = path.join(__dirname, '../data/backups');

/** Extract creation timestamp from a Discord snowflake ID */
function snowflakeToDate(id) {
    try {
        const ms = BigInt(id) >> 22n;
        return new Date(Number(ms) + 1420070400000);
    } catch {
        return null;
    }
}

/** Return true if a string looks like a valid Discord snowflake (17-19 digits) */
function isSnowflake(str) {
    return typeof str === 'string' && /^\d{17,19}$/.test(str);
}

module.exports = {
    name: 'fixdata',
    description: 'Admin command to audit and repair channels.json',
    async execute(message, args) {
        if (!message.member.permissions.has(PermissionsBitField.Flags.Administrator)) {
            return message.reply('This command is only available to admins.');
        }

        const dryRun = !args.includes('--fix');

        // ── 1. Backup ────────────────────────────────────────────────────────
        if (!fs.existsSync(BACKUP_DIR)) fs.mkdirSync(BACKUP_DIR, { recursive: true });
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const backupPath = path.join(BACKUP_DIR, `channels-${timestamp}.json`);
        fs.copyFileSync(DATA_PATH, backupPath);

        // ── 2. Load ──────────────────────────────────────────────────────────
        let raw;
        try {
            raw = JSON.parse(fs.readFileSync(DATA_PATH, 'utf8'));
        } catch (err) {
            return message.reply(`Failed to parse channels.json: ${err.message}`);
        }

        const issues = [];
        const cleaned = {};
        // channelId → userId of the entry that claimed it first
        const seenChannels = new Map();

        for (const [key, entry] of Object.entries(raw)) {
            // ── Skip legacy array key ────────────────────────────────────────
            if (key === 'channels') {
                issues.push(`⚠️ Legacy \`channels\` array key — will be removed`);
                continue;
            }

            // ── Must be a plain object ───────────────────────────────────────
            if (!entry || typeof entry !== 'object' || Array.isArray(entry)) {
                issues.push(`❌ Key \`${key}\`: not an object — will be removed`);
                continue;
            }

            // ── Required snowflake fields ────────────────────────────────────
            // createdAt is NOT required — we derive it from channelId snowflake
            if (!isSnowflake(entry.userId)) {
                issues.push(`❌ Key \`${key}\`: missing or invalid \`userId\` — will be removed`);
                continue;
            }
            if (!isSnowflake(entry.channelId)) {
                issues.push(`❌ Key \`${key}\`: missing or invalid \`channelId\` — will be removed`);
                continue;
            }

            // ── Key/userId mismatch ──────────────────────────────────────────
            // The key should always equal entry.userId. If they differ, one of
            // them has a typo. We trust entry.userId (the value) over the key
            // because the key is generated by the code whereas userId comes from
            // Discord directly. We'll re-key to entry.userId — but only if that
            // slot isn't already occupied by a fully-valid entry.
            const canonicalKey = entry.userId;
            if (key !== canonicalKey) {
                if (cleaned[canonicalKey]) {
                    // The correctly-keyed entry already exists and is valid —
                    // this miskeyed one is the stale/corrupt duplicate, drop it.
                    issues.push(`❌ Key \`${key}\` has mismatched userId \`${canonicalKey}\` AND a valid entry already exists under that userId — dropping miskeyed entry`);
                    continue;
                }
                issues.push(`⚠️ Key \`${key}\` does not match userId \`${canonicalKey}\` — will be re-keyed`);
                // Fall through; we write it under canonicalKey below
            }

            // ── Duplicate userId ─────────────────────────────────────────────
            if (cleaned[canonicalKey]) {
                issues.push(`❌ Duplicate userId \`${canonicalKey}\` — keeping first valid occurrence, discarding this one`);
                continue;
            }

            // ── Duplicate channelId ──────────────────────────────────────────
            if (seenChannels.has(entry.channelId)) {
                const firstOwner = seenChannels.get(entry.channelId);
                issues.push(`❌ Channel \`${entry.channelId}\` claimed by both \`${firstOwner}\` and \`${canonicalKey}\` — keeping \`${firstOwner}\`, removing \`${canonicalKey}\``);
                continue;
            }

            // ── Strip unknown fields, keep only what we need ─────────────────
            const friendsRaw = Array.isArray(entry.friends) ? entry.friends : [];

            // friends: must be snowflakes, unique, and not the owner themselves
            const friendsBefore = friendsRaw.length;
            const friends = [...new Set(
                friendsRaw.filter(id => isSnowflake(id) && id !== canonicalKey)
            )];
            if (friends.length !== friendsBefore) {
                issues.push(`⚠️ Key \`${canonicalKey}\`: friends list cleaned (${friendsBefore} → ${friends.length} entries; removed duplicates, non-snowflakes, or self-reference)`);
            }

            // ── Build clean entry (no createdAt — derived from snowflake) ────
            // We keep createdAt if it was already present and valid, just so
            // existing data isn't noisily changed. But we don't require it.
            const cleanEntry = {
                userId: canonicalKey,
                channelId: entry.channelId,
                friends,
            };

            if (entry.createdAt && !isNaN(Date.parse(entry.createdAt))) {
                cleanEntry.createdAt = entry.createdAt;
            }
            // If createdAt was missing or invalid, we simply omit it.
            // Channel creation time can always be derived: snowflakeToDate(entry.channelId)

            seenChannels.set(entry.channelId, canonicalKey);
            cleaned[canonicalKey] = cleanEntry;
        }

        // ── 3. Build report ──────────────────────────────────────────────────
        const totalBefore = Object.keys(raw).filter(k => k !== 'channels').length;
        const totalAfter = Object.keys(cleaned).length;

        const statusColor = issues.length === 0 ? Colors.Green
            : dryRun ? Colors.Yellow
                : Colors.Orange;

        const embed = new EmbedBuilder()
            .setTitle(`Data audit ${dryRun ? '(dry run — no changes written)' : '(--fix applied)'}`)
            .setColor(statusColor)
            .addFields(
                { name: 'Entries before', value: String(totalBefore), inline: true },
                { name: 'Entries after', value: String(totalAfter), inline: true },
                { name: 'Net change', value: String(totalAfter - totalBefore), inline: true },
                { name: 'Issues found', value: String(issues.length), inline: true },
                { name: 'Backup', value: `\`data/backups/channels-${timestamp}.json\``, inline: false },
            );

        if (!dryRun) {
            embed.addFields({ name: 'Status', value: '✅ channels.json rewritten with clean data', inline: false });
        } else if (issues.length > 0) {
            embed.addFields({ name: 'To apply fixes', value: 'Run `,fixdata --fix`', inline: false });
        }

        await message.reply({ embeds: [embed] });

        // ── 4. Send issues in chunks ─────────────────────────────────────────
        if (issues.length > 0) {
            const CHUNK = 20;
            for (let i = 0; i < issues.length; i += CHUNK) {
                const slice = issues.slice(i, i + CHUNK);
                const issueEmbed = new EmbedBuilder()
                    .setColor(Colors.Yellow)
                    .setTitle(`Issues ${i + 1}–${Math.min(i + CHUNK, issues.length)} of ${issues.length}`)
                    .setDescription(slice.join('\n').substring(0, 4000));
                await message.channel.send({ embeds: [issueEmbed] });
            }
        } else {
            await message.channel.send({
                embeds: [
                    new EmbedBuilder()
                        .setColor(Colors.Green)
                        .setDescription('✅ No issues found — data looks clean.')
                ]
            });
        }

        // ── 5. Write if --fix ────────────────────────────────────────────────
        if (!dryRun) {
            fs.writeFileSync(DATA_PATH, JSON.stringify(cleaned, null, 2), 'utf8');
        }
    },
};